### ISSUE TITLE
Todo from Training

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#154]
- [x] Remove CTA from Footer
- [x] Add Facebook to Footer, get link from ENSI - **Need icon** - see #139 
- [x] Homepage animation make people stand up
- [ ] ~~Apply styles for button so it's more intuitive once pulled in~~ - see #141 
- [x] Add drop-down to Our Services
- [x] No sitemap to be included
- [x] Fix language selector so it's always showing in Webflow
- [x] Fix naming conventions if possible
- [x] Get list together for Emma with special cases to be changed
- [ ] Hook up Typeform and contact form to ENSI Salesforce
- [X] Add accept T&Cs in Contact Us Form (ticked per default) - see #146

**Comment by smypf** [comment]
@jomentallyfriendly Homepage animation make people stand up - What's this>?

**Comment by smypf** [comment]
@jomentallyfriendly Unable to apply button stylings. See #141

**Comment by smypf** [comment]
Completed - Add accept T&Cs in Contact Us Form (ticked per default) - see #146
